### ISSUE TITLE
How to use the pie chart?

### ISSUE THREAD

**Issue by EdwinHoksberg** [insenseanalytics/nova-bar-metrics#1]
Hi, your package works great with drawing bar charts, but I can't figure out how to draw pie charts, as shown in the readme example.
Can you elaborate on that? Thanks.

**Comment by paras-malhotra** [comment]
Hi @EdwinHoksberg, Pie charts are provided by Laravel Nova out of the box (refer the `Partition` class). What this package does is it helps create [frequency distribution](https://en.wikipedia.org/wiki/Frequency_distribution) pie charts using the Partition class

As an example, let's say you have an `age` column in your user table and you would like a frequency distribution pie chart for age. This pie chart would group the age ranges in brackets and display something like: `1-20`: 5000, `21-40`: 6000, etc. which means you have 5,000 users in the 1-20 age group bracket and so on.

To create this pie chart, you can add a metric like so:

```php
use Laravel\Nova\Metrics\Partition;
use Insenseanalytics\NovaBarMetrics\HasFrequencyDistributions;

class UsersByAgeGroup extends Partition
{
  use HasFrequencyDistributions;
  
  public function calculate(Request $request)
  {
    return $this->distributions($request, App\User::class, 'age', 20);
  }
}
```

In the example above, `App\User` is the User model, `age` is the column name for the frequency distribution and `20` is the step size (if you'd like to see the age ranges for every 20 years). This would create a pie chart with the age group ranges.

The `HasFrequencyDistributions` trait makes all of this possible.

You could very easily switch this to bar charts by just extending the `BarChartMetric` class instead. You don't need the `HasFrequencyDistributions` trait for the `BarChartMetric` class.

**Comment by EdwinHoksberg** [comment]
Oh, I was confused, I totally thought you made a _new_ custom pie chart. Thanks for the explanation!
