### ISSUE TITLE
Create generator for cards

### ISSUE THREAD

**Issue by jrmadsen67** [insenseanalytics/nova-bar-metrics#2]
Happy to do a PR if I get time, but anyone else feel free to grab this.

Something like: `artisan nova:value UserCount`

but to work with these metrics

**Comment by jrmadsen67** [comment]
PR https://github.com/insenseanalytics/nova-bar-metrics/pull/3 created for this.

I did everything pretty boilerplate - let me know if you want any tweaks.

Thanks again for the project - been very helpful to us!

**Comment by paras-malhotra** [comment]
Closed in #3
